import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Group } from "./grup.slint";
import { Status } from "./status.slint";
import { Textbox, TextboxLogic } from "./textbox.slint";
import { Connection } from "./connection.slint";
import { Chat } from "./chat.slint";

export { TextboxLogic }
export { Connection }

export component AppWindow inherits Window {
    in-out property <string> chat-user <=> chat.user;
    in-out property <string> chat-irc-address <=> chat.irc-address;
    in property <Connection> chat-irc-status <=> chat.irc-status;
    in property <Connection> chat-pda-status <=> chat.pda-status;
    callback chat-connect <=> chat.connect;
    callback chat-disconnect <=> chat.disconnect;

    title: "Monolith Control Center";
    icon: @image-url("icons/app_icon.png");
    min-width: 400px;
    min-height: 660px;
    background: #292A29;
    padding: 10px;

    Image {
        width: parent.width;
        height: parent.height;
        source: @image-url("images/background.png");
    }
    
    Rectangle {
        width: parent.width;
        height: parent.height;
        border-color: #FFFFFF;
        border-width: 1px;
    }

    Rectangle {
        x: (root.width - min(3, (floor(root.width / 360px))) * 360px) / 2 + 5px;
        y: 20px;

        chat := Chat {
            x: (mod(0, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(0 / max(floor(root.width / 350px), 1)) * 230px);
        }

        Group {
            title: "QUESTS";
            icon: @image-url("./icons/icon_1.png");
            x: (mod(1, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(1 / max(floor(root.width / 350px), 1)) * 230px);
        }

        Group {
            title: "STORAGE";
            icon: @image-url("./icons/icon_2.png");
            x: (mod(2, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(2 / max(floor(root.width / 350px), 1)) * 230px);
        }
    }
}
