import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Group } from "./grup.slint";
import { Status } from "./status.slint";
import { Textbox, TextboxLogic } from "./textbox.slint";

export { TextboxLogic }

export component AppWindow inherits Window {
    title: "Monolith Control Center";
    icon: @image-url("icons/app_icon.png");
    min-width: 400px;
    min-height: 660px;
    background: #292A29;
    padding: 10px;
    
    Image {
        width: parent.width;
        height: parent.height;
        source: @image-url("images/background.png");
    }
    
    Rectangle {
        width: parent.width;
        height: parent.height;
        border-color: #FFFFFF;
        border-width: 1px;
    }

    Rectangle {
        x: (root.width - min(3, (floor(root.width / 360px))) * 360px) / 2 + 5px;
        y: 20px;

        Group {
            title: "CHAT";
            icon: @image-url("./icons/icon_0.png");
            x: (mod(0, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(0 / max(floor(root.width / 350px), 1)) * 230px);
        }

        Group {
            title: "QUESTS";
            icon: @image-url("./icons/icon_1.png");
            x: (mod(1, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(1 / max(floor(root.width / 350px), 1)) * 230px);

            Textbox {
                height: 40px;
                title: "IRC ADDRESS";
                value: "0000.0000.0000";
            }

            Status {
                height: 40px;
                title: "IRC STATUS";
                value: "CONNECTED";
                text-color: #E5C72F;
            }

            Status {
                height: 40px;
                title: "PDA STATUS";
                value: "DISCONNECTED";
                text-color: #D61818;
            }
        }

        Group {
            title: "STORAGE";
            icon: @image-url("./icons/icon_2.png");
            x: (mod(2, max(floor(root.width / 360px), 1)) * 360px);
            y: (floor(2 / max(floor(root.width / 350px), 1)) * 230px);
        }
    }
}
