export component Button inherits Rectangle {
    in property <string> text;
    in property <color> text-color;
    callback clicked();

    background: touch.pressed ? #353635 : touch.has-hover ? #414341 : #353635;
    border-color: touch.pressed ? #fff : touch.has-hover ? #aaa : #888;
    border-width: 2px;
    border-radius: 5px;

    animate border-color { duration: 0.125s; }
    animate background { duration: 0.125s; }

    touch := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;
        clicked => { root.clicked() }
    }

    Text {
        text: root.text;
        color: root.text-color;
        animate color { duration: 0.25s; }
    }
}
