export component Status inherits Rectangle {
    in property <string> title;
    in property <string> value;
    in property <color> text-color;

    border-color: #888;
    border-width: 2px;
    border-radius: 3px;

    Rectangle {
        x: 0px;
        y: 0px;
        width: parent.width / 3;

        border-color: #888;
        border-width: 2px;
        border-radius: 3px;
        border-top-right-radius: 0px;
        border-bottom-right-radius: 0px;

        Text {
            text: root.title;
            color: #888;
        }
    }

    Rectangle {
        x: parent.width / 3;
        width: parent.width - parent.width / 3;

        Text {
            text: root.value;
            color: root.text-color;
            animate color { duration: 0.25s; }
        }
    }
}
